# Generated by Django 4.1.7 on 2023-03-22 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('fathername', models.CharField(max_length=50, null=True)),
                ('mothername', models.CharField(max_length=50, null=True)),
                ('image', models.ImageField(null=True, upload_to='photos')),
                ('mobile', models.BigIntegerField()),
                ('dob', models.DateField()),
                ('course', models.CharField(max_length=50, null=True)),
                ('fee', models.CharField(choices=[('pending', 'pending'), ('installment', 'installment'), ('completed', 'completed')], default='pending', max_length=50, null=True)),
            ],
        ),
    ]
