# Generated by Django 4.1.7 on 2023-04-03 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_admission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='surname',
            new_name='usersname',
        ),
    ]
