# Generated by Django 4.1.7 on 2023-04-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_surname_admission_usersname'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='register',
        ),
    ]
