# Generated by Django 4.1.7 on 2023-04-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
