# Generated by Django 4.1.7 on 2023-04-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_certificate_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificate2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regno', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('course', models.CharField(max_length=100, null=True)),
                ('enroll', models.CharField(max_length=30, null=True)),
                ('grade', models.CharField(max_length=20, null=True)),
                ('duration', models.CharField(max_length=20, null=True)),
                ('date', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
