# Generated by Django 4.1.7 on 2023-04-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_certificate2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='certificate',
        ),
    ]
