# Generated by Django 4.1.7 on 2023-04-29 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_delete_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate2',
            name='image',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
