# Generated by Django 4.1.7 on 2023-04-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_certificate2_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate2',
            name='detail',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
