# Generated by Django 4.1.7 on 2023-04-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_certificate2_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate2',
            name='detail',
            field=models.CharField(choices=[('Typing,Word,Excel,Powerpoint,Outlook & Internet etc.', 'Typing,Word,Excel,Powerpoint,Outlook & Internet etc.'), ('(Ms-Office, Tally with GST, DTP & Internet Technologies)', '(Ms-Office, Tally with GST, DTP & Internet Technologies)'), ('Accounting, Inventory, Payroll, Banking, GST & TDS etc.', 'Accounting, Inventory, Payroll, Banking, GST & TDS etc.'), ('Page-Maker, Corel Draw & Photoshop etc..', 'Page-Maker, Corel Draw & Photoshop etc..'), ('-', '-')], max_length=200, null=True),
        ),
    ]
