# Generated by Django 4.1.7 on 2023-04-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_certificate2_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='fathername',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='fee',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='mothername',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='name',
        ),
        migrations.AlterField(
            model_name='admission',
            name='course',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='usersname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
