# Generated by Django 4.1.7 on 2023-04-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_admission_fathername_remove_admission_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='doa',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='formno',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
