# Generated by Django 4.1.7 on 2023-05-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_admission_doa_admission_formno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='image',
        ),
        migrations.AlterField(
            model_name='admission',
            name='doa',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='dob',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
