# Generated by Django 4.1.7 on 2023-05-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_admission_image_alter_admission_doa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='mobile',
            field=models.BigIntegerField(null=True),
        ),
    ]
