# Generated by Django 4.1.7 on 2023-05-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_admission_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='image',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
