# Generated by Django 4.1.7 on 2023-05-05 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_certificate2_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='mcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='certificate2',
            name='course',
            field=models.CharField(choices=[('BASIC COMPUTER & MS-OFFICE', 'BASIC COMPUTER & MS-OFFICE'), ('DCA (DIPLOMA IN COMPUTER APPLICATION)', 'DCA (DIPLOMA IN COMPUTER APPLICATION)'), ('TALLY ERP & PRIME WITH GST ', 'TALLY ERP & PRIME WITH GST '), ('DTP (Desktop Publishing)', 'DTP (Desktop Publishing)'), ('Java Programming', 'Java Programming'), ('C Programming', 'C Programming'), ('Website Designing', 'Website Designing'), ('DIT (Diploma in Information Technology)', 'DIT (Diploma in Information Technology)'), ('ADCA (ADVANCE DIPLOMA IN COMPUTER APPLICATION)', 'ADCA (ADVANCE DIPLOMA IN COMPUTER APPLICATION)'), ('ADSE (ADVANCE DIPLOMA IN SOFTWARE ENGINEERING)', 'ADSE (ADVANCE DIPLOMA IN SOFTWARE ENGINEERING)'), ('AUTOCAD 2-D & 3-D', 'AUTOCAD 2-D & 3-D'), ('BASIC COMPUTER & TYPING ( ENGLISH )', 'BASIC COMPUTER & TYPING ( ENGLISH )'), ('BASIC COMPUTER & TYPING ( GUJARATI )', 'BASIC COMPUTER & TYPING ( GUJARATI )'), ('BASIC COMPUTER & TYPING ( ENGLISH & GUJARATI )', 'BASIC COMPUTER & TYPING (ENGLISH & GUJARATI )'), ('CCC (CERTIFICATE IN COMPUTER CONCEPT)', 'CCC (CERTIFICATE IN COMPUTER CONCEPT)'), ('LINUX & SHELL PROGRAMMING', 'LINUX & SHELL PROGRAMMING'), ('PYTHON PROGRAMMING', 'PYTHON PROGRAMMING')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificate2',
            name='detail',
            field=models.CharField(choices=[('(Typing,Word,Excel,Powerpoint,Outlook & Internet etc.)', '(Typing,Word,Excel,Powerpoint,Outlook & Internet etc.)'), ('(Ms-Office, Tally with GST, DTP & Internet Technologies)', '(Ms-Office, Tally with GST, DTP & Internet Technologies)'), ('(Accounting, Inventory, Payroll, Banking, GST & TDS etc.)', '(Accounting, Inventory, Payroll, Banking, GST & TDS etc.)'), ('(Page-Maker, Corel Draw & Photoshop etc..)', '(Page-Maker, Corel Draw & Photoshop etc..)'), ('HTML, CSS, JAVA SCRIPT,WORDPRESS,PHOTOSHOP etc.', 'HTML, CSS, JAVA SCRIPT,WORDPRESS,PHOTOSHOP etc.'), ('-', '-')], max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='detailcourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=30)),
                ('detail', models.CharField(max_length=500)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.mcourse')),
            ],
        ),
    ]
