# Generated by Django 4.2.4 on 2023-12-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_certificate2_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate2',
            name='course',
            field=models.CharField(choices=[('BASIC COMPUTER & MS-OFFICE', 'BASIC COMPUTER & MS-OFFICE'), ('DCA (DIPLOMA IN COMPUTER APPLICATION)', 'DCA (DIPLOMA IN COMPUTER APPLICATION)'), ('TALLY ERP & PRIME WITH GST ', 'TALLY ERP & PRIME WITH GST '), ('TALLY ERP WITH GST ', 'TALLY ERP WITH GST '), ('DTP (Desktop Publishing)', 'DTP (Desktop Publishing)'), ('Java Programming', 'Java Programming'), ('C Programming', 'C Programming'), ('C++ Programming', 'C++ Programming'), ('C & C++ Programming', 'C & C++ Programming'), ('C , C++ & Java Programming', 'C , C++  & Java Programming'), ('Website Designing', 'Website Designing'), ('DIT (Diploma in Information Technology)', 'DIT (Diploma in Information Technology)'), ('ADCA (ADVANCE DIPLOMA IN COMPUTER APPLICATION)', 'ADCA (ADVANCE DIPLOMA IN COMPUTER APPLICATION)'), ('ADSE (ADVANCE DIPLOMA IN SOFTWARE ENGINEERING)', 'ADSE (ADVANCE DIPLOMA IN SOFTWARE ENGINEERING)'), ('AUTOCAD 2-D & 3-D', 'AUTOCAD 2-D & 3-D'), ('BASIC COMPUTER & TYPING ( ENGLISH )', 'BASIC COMPUTER & TYPING ( ENGLISH )'), ('BASIC COMPUTER & TYPING ( GUJARATI )', 'BASIC COMPUTER & TYPING ( GUJARATI )'), ('BASIC COMPUTER & TYPING ( ENGLISH & GUJARATI )', 'BASIC COMPUTER & TYPING (ENGLISH & GUJARATI )'), ('CCC (CERTIFICATE IN COMPUTER CONCEPT)', 'CCC (CERTIFICATE IN COMPUTER CONCEPT)'), ('LINUX & SHELL PROGRAMMING', 'LINUX & SHELL PROGRAMMING'), ('PYTHON PROGRAMMING', 'PYTHON PROGRAMMING'), ('MS-OFFICE & TALLY ', 'MS-OFFICE & TALLY ')], max_length=100, null=True),
        ),
    ]
