# Generated by Django 4.2.4 on 2024-05-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_fees_paid_log_alter_certificate2_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='paid_fee',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='total_fee',
            field=models.BigIntegerField(null=True),
        ),
    ]
