# Generated by Django 4.2.4 on 2024-05-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_admission_paid_fee_admission_total_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='batch_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
