# Generated by Django 4.2.4 on 2024-05-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_admission_batch_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paid_log',
            name='fee_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
