# Generated by Django 4.2.4 on 2024-05-15 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_alter_paid_log_fee_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='paid_fee',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='total_fee',
        ),
    ]
