# Generated by Django 4.2.4 on 2024-05-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_admission_paid_fee_remove_admission_total_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate2',
            name='regno',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
