# Generated by Django 4.2.4 on 2024-07-17 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_certificate2_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate2',
            name='detail',
            field=models.CharField(choices=[('(Typing,Word,Excel,Powerpoint,Outlook & Internet etc.)', '(Typing,Word,Excel,Powerpoint,Outlook & Internet etc.)'), ('(Ms-Office, Tally with GST, DTP & Internet Technologies)', '(Ms-Office, Tally with GST, DTP & Internet Technologies)'), ('(Accounting, Inventory, Payroll, Banking, GST & TDS etc.)', '(Accounting, Inventory, Payroll, Banking, GST & TDS etc.)'), ('(Page-Maker, Corel Draw & Photoshop etc..)', '(Page-Maker, Corel Draw & Photoshop etc..)'), ('HTML, CSS, JAVA-Script,Wordpress,Photoshop,Uploading etc.', 'HTML, CSS, JAVA-Script,Wordpress,Photoshop,Uploading etc.'), ('TYPING IN ENGLISH (40 WPM) & GUJARATI (30 WPM)', 'TYPING IN ENGLISH (40 WPM) & GUJARATI (30 WPM)'), ('TYPING IN ENGLISH (35 WPM) & GUJARATI (30 WPM)', 'TYPING IN ENGLISH (35 WPM) & GUJARATI (30 WPM)'), ('--- ', '---')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='certificate2',
            name='grade',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
